# Generated by Django 4.1.7 on 2023-02-25 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
