# Generated by Django 4.1.7 on 2023-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_postviews_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='post_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
