# Generated by Django 4.1.7 on 2023-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_postviews_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postviews',
            name='post_views',
            field=models.BooleanField(default=False),
        ),
    ]
